[envs]
[envs.zsh]
    exe_exists = ["zsh"]
    # path_exists = ["${HOME}/.config/zsh"]

[envs.um]
    exe_exists = ["um"]
  # or / [[]] = and
    path_exists = [
       "/Users/lucasburns/.config/um",
       "/Users/lucasburns/.um"
    ]

[envs.macos]
    os = ["macos"]

[envs.unix]
    os = ["linux", "macos", "freebsd"]
    env = [
        { var = "HOME" },
        { var = "XDG_CONFIG_HOME" }
    ]

[hoards]
# [hoards.zsh]
#     [hoards.zsh.aliases]
#         "zsh|macos" = "${ASDF:-$ZDOTDIR}/zsh.d/aliases.zsh"


[hoards.test]
  [hoards.test.config]
      "follow_links" = true
      "max_depth" = 5
      "exclude" = ["*exclude*"]
    [hoards.test.config.encryption]
        "encrypt" = "symmetric"
        "encrypt_pass" = "lmao"
    [hoards.test.lmao]
        "macos|um" = "${HOME}/test/lmao"
        # [hoards.test.lmao.config]
        # "follow_links" = true

# [hoards.single]
#     "macos|um" = "${HOME}/test/src"

    # [hoards.um.pages]
    #     "macos|um" = "${XDG_CONFIG_HOME}/um/pages"
    # [hoards.um.conf]
    #     "macos|um" = "${XDG_CONFIG_HOME}/um/umconfig"

# [hoards.zsh.git_token]
#     "zsh|macos" = "$ZDOTDIR/zsh.d/git-token.zsh"
# [hoards.zsh.bindings]
#     "zsh|macos" = "~/.config/zsh/zsh.d/keybindings.zsh"

# vim: ft=toml:et:sw=0:ts=4:sts=4:fdm=marker:fmr={{{,}}}:
