# Global configuration
#
# ignores = array of patterns to ignore that apply to every hoard
# These are patterns that are found in .gitignore files, not a regex patter
# like 'exlcude' below
global_config:
  ignores: [.git/]

# Lists of environment names.
#
# Environment names in lists together cannot appear in the same environment condition string.
# For example, you cannot specify a path that matches both Vim and Neovim.
exclusivity:
  # Neovim takes priority over Vim.
  - - neovim
    - vim
  # Flatpak steam installation takes priority over "native" install.
  - - steam_flatpak
    - steam

envs:
  # Match if `fish` is somewhere in $PATH.
  fish:
    exe_exists:
      - fish
  # Detect "neovim" if AT LEAST one of `nvim` or `nvim-qt` exists in $PATH.
  # This is parsed as `nvim OR nvim-qt`.
  neovim:
    exe_exists:
      - nvim
      - nvim-qt
  vim:
    # If at LEAST one of them exists
    exe_exists:
      - vim
      - gvim
  # Match itch if BOTH of these paths exist.
  # These paths are parsed as (first) AND (second).
  itch:
    path_exists:
      - - /home/shadow53/.itch
        - /home/shadow53/.local/share/applications/io.itch.itch.desktop
  openrct2:
    exe_exists:
      - openrct2
  scummvm:
    exe_exists:
      - scummvm
  steam:
    exe_exists:
      - steam
  steam_flatpak:
    exe_exists:
      - flatpak
    path_exists:
      - /home/shadow53/.var/app/com.valvesoftware.Steam
  # OPERATING SYSTEMS
  # See https://doc.rust-lang.org/stable/std/env/consts/constant.OS.html for some possible
  # values for `os`.
  windows:
    os:
      - windows
  linux:
    os:
      - linux
  macos:
    os:
      - macos
  freebsd:
    os:
      - freebsd
  # Is Unix if one of the OSes match AND both of the environment variables exist.
  # You can also require a specific value for the variable with
  # { var = "SOME_VAR", expected = "the var value" }
  unix:
    env:
      - var: HOME
      - var: XDG_CONFIG_HOME
    os:
      - linux
      - macos
      - freebsd
hoards:
  fish:
    # A configuration for each hoard is used
    # Note that `config` is a reserved name for a hoard
    config:
      # Whether or not to follow symlinks
      follow_links: true
      # Whether or not to skip hidden files
      hidden: true
      # Pattern of files to only include
      pattern: "*.txt"
      # Whether the pattern is to be interpreted as a regex or a glob
      regex: true
      # Max depth to traverse
      max_depth: 2
      # Whether the pattern should be case sensitive or not
      case_sensitive: false
      # Alternate ways of writing it
      exclude:
        - "*john*"
      # exclude = ["*exclude*"]

      # Is being worked on
      encryption:
        encrypt: symmetric
        encrypt_pass: lmao

  # Both `fish|linux` and `linux|fish` match the same way and are considered
  # the same condition internally.
    confdir:
      linux|fish: /home/shadow53/.config/fish/conf.d
    functions:
      fish|linux: /home/shadow53/.config/fish/functions
  fonts:
    linux: /home/shadow53/.local/share/fonts
  game_saves:
    apotheon:
      linux|steam: /home/shadow53/.local/share/Apotheon/SavedGames
      linux|steam_flatpak: /home/shadow53/.local/share/Apotheon/SavedGames
    death_and_taxes:
      linux|itch: /home/shadow53/.config/unity3d/Placeholder Gameworks/Death and Taxes/Saves
    dnd_lesbians:
      linux|itch: /home/shadow53/.renpy/DnDLes-1580852644
    lovers_dangerous_spacetime:
      linux|steam: /home/shadow53/.local/share/LoversInADangerousSpacetime/save.dat
      linux|steam_flatpak: /home/shadow53/.local/share/LoversInADangerousSpacetime/save.dat
    scummvm:
      linux|scummvm: /home/shadow53/.local/share/scummvm/saves
    spacechem:
      linux|steam: /home/shadow53/.local/share/Zachtronics Industries/SpaceChem/save
      linux|steam_flatpak: /home/shadow53/.local/share/Zachtronics Industries/SpaceChem/save
    superliminal:
      linux|steam: /home/shadow53/.config/unity3d/PillowCastle/SuperliminalSteam/Clouds
      linux|steam_flatpak: /home/shadow53/.config/unity3d/PillowCastle/SuperliminalSteam/Clouds
    they_bleed_pixels:
      linux|itch: /home/shadow53/.local/share/TheyBleedPixels/savedata
    wizard_of_legend:
      linux|steam: /home/shadow53/.config/unity3d/Contingent99/Wizard of Legend/128757792
      linux|steam_flatpak: /home/shadow53/.config/unity3d/Contingent99/Wizard of Legend/128757792
  git:
    linux: /home/shadow53/.gitconfig
  latex:
    awesomecv:
      linux: /home/shadow53/.texmf/tex/awesome-cv
    fonts:
      linux: /home/shadow53/.texmf/fonts
  newsboat:
    linux: /home/shadow53/.newsboat/config
  qemu:
    script:
      linux: /home/shadow53/.bin/vm
    configs:
      linux: /home/shadow53/.config/qemu
  vim:
    init:
      linux|neovim: /home/shadow53/.config/nvim/init.vim
      linux|vim: /home/shadow53/.vimrc
      windows|neovim: C:\Users\Shadow53\AppData\Local\nvim\init.vim
      windows|vim: C:\Users\Shadow53\.vim\_vimrc
    configdir:
      windows|neovim: C:\Users\Shadow53\AppData\Local\nvim\config
      windows|vim: C:\Users\Shadow53\.vim\config
      linux|neovim: /home/shadow53/.config/nvim/config
      linux|vim: /home/shadow53/.vim/config
    templates:
      windows|neovim: C:\Users\Shadow53\AppData\Local\nvim\templates
      windows|vim: C:\Users\Shadow53\.vim\templates
      linux|neovim: /home/shadow53/.config/nvim/templates
      linux|vim: /home/shadow53/.vim/templates
  vorta:
    linux: /home/shadow53/.local/share/Vorta/settings.db
